\documentclass{article}
\usepackage{amsfonts}
\usepackage{hyperref} 
\begin{document}
\SweaveOpts{concordance=TRUE}
\section{Introduction}

The density of these loans is as follows:

<<echo=FALSE>>=
require(jsonlite)
base='./'
base='~/Documents/Code/rust/credit_faas_demo/docs/'
#results=fromJSON(readLines(paste0(base, 'loan_density.json')))
results=fromJSON(paste0(base, 'loan_density.json'))
@

<<echo=FALSE, fig=TRUE>>=
plot(results$x, results$density, type='l')

@


\end{document}